name: Build Keenetic SDK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential git curl wget unzip bzip2 lzip patch perl python3 jq \
          sed gawk bc tar autoconf automake libtool m4 findutils util-linux \
          ncurses-dev libssl-dev zlib1g-dev pkg-config file

    - name: Prepare Keenetic SDK
      run: |
        cd $GITHUB_WORKSPACE
        # Убедимся, что SDK распакован и готов
        if [ ! -d keenetic-sdk ]; then
          echo "Keenetic SDK directory not found!"
          exit 1
        fi
        cd keenetic-sdk

    - name: Configure SDK
      run: |
        make menuconfig || make defconfig

    - name: Build SDK
      run: |
        cd keenetic-sdk
        make -j$(nproc) package/huawei-integration/compile

    - name: List built packages
      run: |
        cd keenetic-sdk/bin/mt7621/packages
        ls -lh
