name: Build Keenetic Huawei Integration Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Keenetic SDK
        run: |
          git clone --depth 1 --branch 4.03 https://github.com/keenetic/keenetic-sdk.git
          mkdir -p keenetic-sdk/package/keenetic-huawei-integration
          find . -maxdepth 1 -not -path "./keenetic-sdk" -not -path . -not -path "./.git" -exec cp -r {} keenetic-sdk/package/keenetic-huawei-integration/ \;
          cd keenetic-sdk
          mkdir -p package/libjson-c
          curl -sL https://raw.githubusercontent.com/openwrt/openwrt/main/package/libs/libjson-c/Makefile > package/libjson-c/Makefile
          mkdir -p package/lua
          curl -sL https://raw.githubusercontent.com/openwrt/openwrt/main/package/utils/lua/Makefile > package/lua/Makefile
          mkdir -p package/libubox
          curl -sL https://raw.githubusercontent.com/openwrt/openwrt/main/package/libs/libubox/Makefile > package/libubox/Makefile
          mkdir -p package/uci
          curl -sL https://raw.githubusercontent.com/openwrt/openwrt/main/package/system/uci/Makefile > package/uci/Makefile
          sudo apt update
          sudo apt install -y build-essential git python3 attr bc curl gawk libhtml-parser-perl libjson-perl libncurses-dev libssl-dev libxml-libxml-perl subversion unzip zlib1g-dev make gcc lzip gperf protobuf-c-compiler flex bison util-linux
          echo "Listing available devices..."
          ./configure.sh -l
          echo "Running configure.sh for KN-2311..."
          ./configure.sh KN-2311 || {
            echo "configure.sh for KN-2311 failed, trying preset 'all'..."
            ./configure.sh -p all || { echo "configure.sh with preset 'all' failed"; exit 1; }
          }
          if [ ! -f .config ]; then
            echo ".config file not created!"
            exit 1
          fi
          echo ".config file created successfully"
          echo "Running make oldconfig to sync configuration..."
          make oldconfig
          if [ $? -ne 0 ]; then
            echo "make oldconfig failed!"
            exit 1
          fi
          echo "make oldconfig completed successfully"

      - name: Build OPKG package
        run: |
          cd keenetic-sdk
          make package/keenetic-huawei-integration/clean V=s
          make package/keenetic-huawei-integration/compile V=s

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: huawei-integration
          path: keenetic-sdk/bin/packages/mipsel/keenetic-huawei-integration_1.0-1_mipsel.ipk

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: keenetic-sdk/bin/packages/mipsel/keenetic-huawei-integration_1.0-1_mipsel.ipk
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Auto-generated release for Huawei Integration OPKG package.
            Download `keenetic-huawei-integration_1.0-1_mipsel.ipk` below for Keenetic routers (Hero 4G+, Skipper 4G, Explorer 4G, Runner 4G) to integrate with Huawei routers (B636-336, B535-232a-LTE, B530-336, B320-323).
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
