name: Build Keenetic Huawei Integration Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3 attr bc curl gawk \
            libhtml-parser-perl libjson-perl libncurses-dev libssl-dev \
            libxml-libxml-perl subversion unzip zlib1g-dev make gcc lzip gperf \
            protobuf-c-compiler flex bison util-linux tree

      - name: Clone Keenetic SDK
        run: |
          git clone --depth 1 --branch 4.03 https://github.com/keenetic/keenetic-sdk.git

      - name: Prepare package in SDK
        run: |
          mkdir -p keenetic-sdk/package/huawei-integration/files
          # Копируем Makefile пакета внутрь папки пакета
          cp Makefile keenetic-sdk/package/huawei-integration/
          # Копируем файлы пакета
          cp -r files/* keenetic-sdk/package/huawei-integration/files/
          echo "Package structure:"
          tree -L 3 keenetic-sdk/package/huawei-integration

      - name: Configure SDK
        run: |
          cd keenetic-sdk
          # Ссылка на системный flock для сборки
          mkdir -p staging_dir/host/bin
          ln -sf /usr/bin/flock staging_dir/host/bin/flock

          echo "Listing available devices..."
          ./configure.sh -l

          echo "Running configure.sh for KN-2311..."
          ./configure.sh KN-2311 || {
            echo "Preset 'KN-2311' failed, trying 'all'..."
            ./configure.sh -p all || { echo "Preset 'all' failed"; exit 1; }
          }

          if [ ! -f .config ]; then
            echo ".config not created!"
            exit 1
          fi
          echo ".config created successfully"

      - name: Sync SDK configuration
        run: |
          cd keenetic-sdk
          echo "[*] Synchronizing .config..."
          make defconfig

      - name: Build toolchain
        run: |
          cd keenetic-sdk
          echo "[*] Building toolchain..."
          make toolchain/install -j1

      - name: Build package
        run: |
          cd keenetic-sdk
          echo "[*] Cleaning previous builds..."
          make package/huawei-integration/clean || true
          echo "[*] Building huawei-integration package..."
          make package/huawei-integration/compile V=s

      - name: Verify artifact
        run: |
          ARTIFACT="keenetic-sdk/bin/packages/mipsel/huawei-integration_1.0-1_mipsel.ipk"
          if [ ! -f "$ARTIFACT" ]; then
            echo "Error: artifact not found!"
            exit 1
          fi
          ls -lh "$ARTIFACT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: huawei-integration
          path: keenetic-sdk/bin/packages/mipsel/huawei-integration_1.0-1_mipsel.ipk

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: keenetic-sdk/bin/packages/mipsel/huawei-integration_1.0-1_mipsel.ipk
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Auto-generated release for Huawei Integration OPKG package.
            Download `huawei-integration_1.0-1_mipsel.ipk` for Keenetic routers.
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
