name: Build Keenetic SDK

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          automake \
          autoconf \
          libtool \
          gnu-findutils \
          wget \
          curl \
          tar \
          git \
          pkg-config \
          bc \
          bison \
          flex \
          python3 \
          python3-pip \
          gawk \
          sed \
          flock

    - name: Locate or prepare Keenetic SDK
      run: |
        # Проверяем, есть ли папка keenetic-sdk
        if [ -d "$GITHUB_WORKSPACE/keenetic-sdk" ]; then
          echo "Keenetic SDK found!"
        elif [ -f "$GITHUB_WORKSPACE/keenetic-sdk.tar.gz" ]; then
          echo "Extracting SDK archive..."
          tar -xzf "$GITHUB_WORKSPACE/keenetic-sdk.tar.gz"
        else
          echo "Error: Keenetic SDK not found!"
          exit 1
        fi

    - name: Enter SDK directory
      working-directory: $GITHUB_WORKSPACE/keenetic-sdk
      run: pwd

    - name: Configure and build SDK
      working-directory: $GITHUB_WORKSPACE/keenetic-sdk
      run: |
        make menuconfig || true
        make defconfig
        make toolchain/install -j$(nproc)
        make -j$(nproc)
