name: Build Keenetic Huawei Integration Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential git python3 attr bc curl gawk \
            libhtml-parser-perl libjson-perl libncurses-dev \
            libssl-dev libxml-libxml-perl subversion unzip zlib1g-dev \
            make gcc lzip gperf protobuf-c-compiler flex bison util-linux \
            sed autoconf automake libtool pkg-config

      - name: Set up Keenetic SDK
        run: |
          git clone --depth 1 --branch 4.03 https://github.com/keenetic/keenetic-sdk.git
          mkdir -p keenetic-sdk/package/huawei-integration
          find . -maxdepth 1 -not -path "./keenetic-sdk" -not -path . -not -path "./.git" \
            -exec cp -r {} keenetic-sdk/package/huawei-integration/ \;

      - name: Fix flock for SDK
        run: |
          mkdir -p keenetic-sdk/staging_dir/host/bin
          ln -s /usr/bin/flock keenetic-sdk/staging_dir/host/bin/flock

      - name: Configure SDK for KN-2311
        run: |
          cd keenetic-sdk
          ./configure.sh KN-2311 || ./configure.sh -p all
          if [ ! -f .config ]; then
            echo ".config not found!"
            exit 1
          fi
          make defconfig

      - name: Build toolchain
        run: |
          cd keenetic-sdk
          make toolchain/install

      - name: Build Huawei Integration package
        run: |
          cd keenetic-sdk
          make package/huawei-integration/clean || true
          make package/huawei-integration/compile V=s

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: huawei-integration
          path: keenetic-sdk/bin/packages/mipsel/huawei-integration_1.0-1_mipsel.ipk

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: keenetic-sdk/bin/packages/mipsel/huawei-integration_1.0-1_mipsel.ipk
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Auto-generated release for Huawei Integration OPKG package.
            Download `huawei-integration_1.0-1_mipsel.ipk` below for Keenetic routers.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
