name: Build Keenetic Huawei Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PATH: ${{ github.workspace }}/keenetic-sdk/staging_dir/host/bin:$PATH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git curl wget unzip bzip2 lzip bc \
          python3 perl automake autoconf gperf libncurses5-dev libssl-dev \
          pkg-config gawk gettext sed gawk findutils attr xxd libtool flex

    - name: Enter SDK directory
      run: cd keenetic-sdk

    - name: Build toolchain
      run: |
        cd keenetic-sdk
        make toolchain V=s

    - name: Build Huawei integration package
      run: |
        cd keenetic-sdk
        make package/huawei-integration/compile V=s

    - name: List generated packages
      run: ls -l keenetic-sdk/bin/mt7621/packages
