name: Build Keenetic SDK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

    steps:
      # 1. Установим базовые утилиты
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            curl \
            wget \
            unzip \
            bzip2 \
            lzip \
            python3 \
            python3-pip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            gawk \
            sed \
            tar \
            bc \
            xxd \
            attr \
            gcc \
            g++ \
            flex \
            bison \
            gettext \
            curl \
            jq \
            gnu-findutils \
            file \
            libncurses5-dev \
            zlib1g-dev \
            libssl-dev \
            flock \
            protobuf-c-compiler

      # 2. Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 3. Переходим в каталог SDK
      - name: Enter keenetic-sdk
        run: |
          cd keenetic-sdk
          pwd

      # 4. Сборка SDK
      - name: Build Keenetic SDK
        run: |
          cd keenetic-sdk
          # Синхронизация конфигурации
          make defconfig
          # Установка toolchain
          make toolchain/install
          # Сборка пакета huawei-integration
          make package/huawei-integration/compile
