name: Build Keenetic Huawei Integration Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Keenetic SDK
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3 attr bc curl gawk \
            libhtml-parser-perl libjson-perl libncurses-dev libssl-dev \
            libxml-libxml-perl subversion unzip zlib1g-dev make gcc lzip gperf \
            protobuf-c-compiler flex bison tree util-linux

          git clone --depth 1 --branch 4.03 https://github.com/keenetic/keenetic-sdk.git

          # Переносим исходники пакета внутрь SDK
          mkdir -p keenetic-sdk/package/huawei-integration/files
          cp -r files/* keenetic-sdk/package/huawei-integration/files/

          cd keenetic-sdk

          # Создаём символическую ссылку на системный flock для SDK
          mkdir -p staging_dir/host/bin
          ln -s /usr/bin/flock staging_dir/host/bin/flock

          echo "Listing available devices..."
          ./configure.sh -l
          echo "Running configure.sh for KN-2311..."
          ./configure.sh KN-2311 || {
            echo "configure.sh for KN-2311 failed, trying preset 'all'..."
            ./configure.sh -p all || { echo "configure.sh with preset 'all' failed"; exit 1; }
          }

          if [ ! -f .config ]; then
            echo ".config file not created!"
            exit 1
          fi
          echo ".config file created successfully"

      - name: Show package structure
        run: |
          cd keenetic-sdk
          tree -L 3 package/huawei-integration

      - name: Build toolchain and OPKG package
        run: |
          cd keenetic-sdk
          echo "[*] Сборка toolchain..."
          make toolchain/install -j1
          echo "[*] Сборка пакета huawei-integration..."
          make package/huawei-integration/compile V=s

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: huawei-integration
          path: keenetic-sdk/bin/packages/mipsel/huawei-integration_1.0-1_mipsel.ipk

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: keenetic-sdk/bin/packages/mipsel/huawei-integration_1.0-1_mipsel.ipk
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Auto-generated release for Huawei Integration OPKG package.
            Download `huawei-integration_1.0-1_mipsel.ipk` below for Keenetic routers (Hero 4G+, Skipper 4G, Explorer 4G, Runner 4G) to integrate with Huawei routers (B636-336, B535-232a-LTE, B530-336, B320-323).
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
