name: Build Keenetic Huawei Integration Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Keenetic SDK
        run: |
          git clone --depth 1 --branch 4.03 https://github.com/keenetic/keenetic-sdk.git
          mkdir -p keenetic-sdk/package/keenetic-huawei-integration
          find . -maxdepth 1 -not -path "./keenetic-sdk" -not -path . -not -path "./.git" -exec cp -r {} keenetic-sdk/package/keenetic-huawei-integration/ \;
          cd keenetic-sdk
          mkdir -p package/libjson-c
          curl -sL https://raw.githubusercontent.com/openwrt/openwrt/openwrt-23.05/package/libs/libjson-c/Makefile > package/libjson-c/Makefile
          mkdir -p package/lua
          curl -sL https://raw.githubusercontent.com/openwrt/openwrt/openwrt-23.05/package/utils/lua/Makefile > package/lua/Makefile
          mkdir -p package/libubox
          curl -sL https://raw.githubusercontent.com/openwrt/openwrt/openwrt-23.05/package/libs/libubox/Makefile > package/libubox/Makefile
          mkdir -p package/uci
          curl -sL https://raw.githubusercontent.com/openwrt/openwrt/openwrt-23.05/package/system/uci/Makefile > package/uci/Makefile
          sudo apt update
          sudo apt install -y build-essential git python3 attr bc curl gawk libhtml-parser-perl libjson-perl libncurses-dev libssl-dev libxml-libxml-perl subversion unzip zlib1g-dev make gcc g++ lzip gperf protobuf-c-compiler flex bison util-linux cmake libc-dev gcc-multilib g++-multilib
          echo "Checking if flock is installed..."
          if command -v flock >/dev/null 2>&1; then
            echo "flock found at $(which flock)"
          else
            echo "flock NOT found in system, exiting..."
            exit 1
          fi
          echo "Ensuring staging_dir/host/bin exists..."
          mkdir -p staging_dir/host/bin
          echo "Copying flock to staging_dir/host/bin..."
          sudo cp $(which flock) staging_dir/host/bin/ || {
            echo "Failed to copy flock to staging_dir/host/bin/"
            echo "Checking if staging_dir/host/bin is writable..."
            ls -ld staging_dir/host/bin/
            exit 1
          }
          echo "flock copied successfully to staging_dir/host/bin/"
          echo "Listing available devices..."
          ./configure.sh -l
          echo "Running configure.sh for KN-2311..."
          ./configure.sh KN-2311 > configure.log 2>&1 || {
            echo "configure.sh for KN-2311 failed, see configure.log"
            cat configure.log
            echo "Trying preset 'all'..."
            ./configure.sh -p all > configure_all.log 2>&1 || { echo "configure.sh with preset 'all' failed"; cat configure_all.log; exit 1; }
          }
          if [ ! -f .config ]; then
            echo ".config file not created!"
            exit 1
          fi
          echo ".config file created successfully"
          echo "Checking .config for mipsel architecture..."
          grep -E 'CONFIG_TARGET_mipsel|CONFIG_ARCH="mipsel"' .config || echo "No mipsel configuration found in .config"
          cat .config
          echo "Running make oldconfig to sync configuration..."
          make oldconfig
          if [ $? -ne 0 ]; then
            echo "make oldconfig failed!"
            exit 1
          fi
          echo "make oldconfig completed successfully"

      - name: Build toolchain
        run: |
          cd keenetic-sdk
          echo "Building tools..."
          make tools/install V=s 2>&1 | tee tools_install.log || { echo "make tools/install failed, see tools_install.log"; cat tools_install.log; exit 1; }
          echo "Building toolchain..."
          make toolchain/install V=s 2>&1 | tee toolchain_install.log || { echo "make toolchain/install failed, see toolchain_install.log"; cat toolchain_install.log; exit 1; }
          echo "Listing contents of staging_dir/toolchain-mipsel-linux-musl_musl/bin to verify compiler..."
          ls -l staging_dir/toolchain-mipsel-linux-musl_musl/bin/ || { echo "toolchain directory not found"; exit 1; }
          echo "Listing contents of staging_dir/host/bin..."
          ls -l staging_dir/host/bin/
          echo "Checking for mipsel compiler..."
          if [ -f staging_dir/toolchain-mipsel-linux-musl_musl/bin/mipsel-linux-musl-gcc ]; then
            echo "mipsel-linux-musl-gcc found"
          else
            echo "mipsel-linux-musl-gcc NOT found, exiting..."
            exit 1
          fi

      - name: Debug directory contents
        run: |
          cd keenetic-sdk
          echo "Listing contents of package directory:"
          ls -R package/
          echo "Listing contents of package/keenetic-huawei-integration:"
          ls -R package/keenetic-huawei-integration/
          echo "Checking Makefile existence:"
          if [ -f package/keenetic-huawei-integration/Makefile ]; then
            echo "Makefile found in package/keenetic-huawei-integration"
            cat package/keenetic-huawei-integration/Makefile
          else
            echo "Makefile NOT found in package/keenetic-huawei-integration"
            exit 1
          fi
          echo "Listing contents of staging_dir/host/bin:"
          ls -l staging_dir/host/bin/

      - name: Build OPKG package
        run: |
          cd keenetic-sdk
          make package/keenetic-huawei-integration/clean V=s
          make package/keenetic-huawei-integration/compile V=s

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: keenetic-huawei-integration
          path: keenetic-sdk/bin/packages/mipsel/keenetic-huawei-integration_1.0-1_mipsel.ipk

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: keenetic-sdk/bin/packages/mipsel/keenetic-huawei-integration_1.0-1_mipsel.ipk
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Auto-generated release for Huawei Integration OPKG package.
            Download `keenetic-huawei-integration_1.0-1_mipsel.ipk` below for Keenetic routers (Hero 4G+, Skipper 4G, Explorer 4G, Runner 4G) to integrate with Huawei routers (B636-336, B535-232a-LTE, B530-336, B320-323).
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
