name: Build Keenetic Huawei Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install basic utilities
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          tar curl wget git build-essential bzip2 lzip bc \
          python3 perl automake autoconf gperf libncurses5-dev libssl-dev \
          pkg-config gawk gettext sed gawk findutils attr xxd libtool flex \
          unzip

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Enter SDK directory
      run: cd keenetic-sdk

    - name: Prepare SDK environment
      run: |
        cd keenetic-sdk
        # Обновляем конфигурацию, чтобы избежать "out of sync" ошибок
        make defconfig

    - name: Build toolchain
      run: |
        cd keenetic-sdk
        make toolchain V=s

    - name: Build Huawei integration package
      run: |
        cd keenetic-sdk
        make package/huawei-integration/compile V=s

    - name: List generated packages
      run: ls -l keenetic-sdk/bin/mt7621/packages
