name: Build Keenetic SDK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          git \
          curl \
          unzip \
          bzip2 \
          lzip \
          ncurses-dev \
          libssl-dev \
          libncurses5-dev \
          gawk \
          attr \
          bc \
          file \
          pkg-config \
          python3 \
          perl \
          automake \
          autoconf \
          libtool \
          gettext \
          curl \
          jq \
          xxd \
          sudo \
          libz-dev \
          flex \
          bison \
          rsync \
          subversion \
          unzip \
          wget \
          gperf

    - name: Fix host binaries for SDK
      run: |
        mkdir -p keenetic-sdk/staging_dir/host/bin
        ln -s /usr/bin/flock keenetic-sdk/staging_dir/host/bin/flock
        ln -s /usr/bin/sed keenetic-sdk/staging_dir/host/bin/sed
        ln -s /usr/bin/mkdir keenetic-sdk/staging_dir/host/bin/mkdir

    - name: Build toolchain
      run: |
        cd keenetic-sdk
        make toolchain/install V=s

    - name: Verify cross-compiler
      run: |
        ls -l staging_dir/toolchain-mipsel-linux-musl/bin/mipsel-ndms-linux-musl-gcc

    - name: Build Huawei integration package
      run: |
        cd keenetic-sdk
        make package/huawei-integration/compile V=s
